//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db3.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class authorisation
    {
        public authorisation()
        {
            this.clients = new HashSet<clients>();
            this.emploees = new HashSet<emploees>();
        }
    
        public long authorisation_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<clients> clients { get; set; }
        public virtual ICollection<emploees> emploees { get; set; }
    }
}
