//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db3.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientsTours
    {
        public long client_id { get; set; }
        public long tour_id { get; set; }
        public System.DateTime dateStart { get; set; }
        public System.DateTime dateEnd { get; set; }
        public long tourHotel_id { get; set; }
        public long clientTour_id { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual tourHotel tourHotel { get; set; }
        public virtual tours tours { get; set; }
    }
}
