//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db3.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientsHotels
    {
        public long client_id { get; set; }
        public long room_id { get; set; }
        public System.DateTime dateStart { get; set; }
        public System.DateTime dateEnd { get; set; }
        public long hotel_id { get; set; }
        public long clientHotel_id { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual hotels hotels { get; set; }
        public virtual rooms rooms { get; set; }
    }
}
