//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db3.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class countres
    {
        public countres()
        {
            this.kurorts = new HashSet<kurorts>();
        }
    
        public long country_id { get; set; }
        public string country { get; set; }
    
        public virtual ICollection<kurorts> kurorts { get; set; }
    }
}
