//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db3.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class kurorts
    {
        public kurorts()
        {
            this.hotels = new HashSet<hotels>();
            this.tours = new HashSet<tours>();
        }
    
        public long kurort_id { get; set; }
        public long country_id { get; set; }
    
        public virtual countres countres { get; set; }
        public virtual ICollection<hotels> hotels { get; set; }
        public virtual ICollection<tours> tours { get; set; }
    }
}
