//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db3.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tour1Entities : DbContext
    {
        public tour1Entities()
            : base("name=tour1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<airlines> airlines { get; set; }
        public DbSet<authorisation> authorisation { get; set; }
        public DbSet<clients> clients { get; set; }
        public DbSet<clientsHotels> clientsHotels { get; set; }
        public DbSet<clientsTours> clientsTours { get; set; }
        public DbSet<countres> countres { get; set; }
        public DbSet<emploees> emploees { get; set; }
        public DbSet<hotels> hotels { get; set; }
        public DbSet<hotels_tours> hotels_tours { get; set; }
        public DbSet<kurorts> kurorts { get; set; }
        public DbSet<programms> programms { get; set; }
        public DbSet<rooms> rooms { get; set; }
        public DbSet<roomTypes> roomTypes { get; set; }
        public DbSet<specialities> specialities { get; set; }
        public DbSet<statuses> statuses { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tourEmploees> tourEmploees { get; set; }
        public DbSet<tourHotel> tourHotel { get; set; }
        public DbSet<tours> tours { get; set; }
    }
}
