//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db3.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rooms
    {
        public rooms()
        {
            this.clientsHotels = new HashSet<clientsHotels>();
        }
    
        public long room_id { get; set; }
        public decimal costPerNight { get; set; }
        public long roomType_id { get; set; }
        public long hotel_id { get; set; }
        public string roomNumber { get; set; }
        public bool isReserved { get; set; }
        public bool isFree { get; set; }
        public Nullable<System.DateTime> dateFree { get; set; }
    
        public virtual ICollection<clientsHotels> clientsHotels { get; set; }
        public virtual hotels hotels { get; set; }
        public virtual roomTypes roomTypes { get; set; }
    }
}
