//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db3.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomTypes
    {
        public roomTypes()
        {
            this.rooms = new HashSet<rooms>();
        }
    
        public long roomType_id { get; set; }
        public int numberOfSeats { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<rooms> rooms { get; set; }
    }
}
