//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db3.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class specialities
    {
        public specialities()
        {
            this.emploees = new HashSet<emploees>();
        }
    
        public long speciality_id { get; set; }
        public string speciality { get; set; }
    
        public virtual ICollection<emploees> emploees { get; set; }
    }
}
