//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db3.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class statuses
    {
        public statuses()
        {
            this.hotels = new HashSet<hotels>();
        }
    
        public long status_id { get; set; }
        public int status { get; set; }
    
        public virtual ICollection<hotels> hotels { get; set; }
    }
}
