//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db3.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tours
    {
        public tours()
        {
            this.clientsTours = new HashSet<clientsTours>();
            this.hotels_tours = new HashSet<hotels_tours>();
        }
    
        public long tour_id { get; set; }
        public long kurort_id { get; set; }
        public long airline_id { get; set; }
        public string tourName { get; set; }
        public string tourDescription { get; set; }
        public long tourEmploee_id { get; set; }
        public decimal cost { get; set; }
        public Nullable<bool> isEnabled { get; set; }
        public Nullable<long> program_id { get; set; }
    
        public virtual airlines airlines { get; set; }
        public virtual ICollection<clientsTours> clientsTours { get; set; }
        public virtual ICollection<hotels_tours> hotels_tours { get; set; }
        public virtual kurorts kurorts { get; set; }
        public virtual programms programms { get; set; }
        public virtual tourEmploees tourEmploees { get; set; }
    }
}
