//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db3.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tourHotel
    {
        public tourHotel()
        {
            this.clientsTours = new HashSet<clientsTours>();
        }
    
        public long tourHotel_id { get; set; }
        public long tour_id { get; set; }
        public string hotel_id { get; set; }
    
        public virtual ICollection<clientsTours> clientsTours { get; set; }
    }
}
