//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db3.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tourEmploees
    {
        public tourEmploees()
        {
            this.tours = new HashSet<tours>();
        }
    
        public long tourEmploee_id { get; set; }
        public long emploee_id { get; set; }
    
        public virtual emploees emploees { get; set; }
        public virtual ICollection<tours> tours { get; set; }
    }
}
